version: "3.8"
services:
  mongodb:
    container_name: modellfabrik_mongodb
    hostname: modellfabrik-db
    image: mongo:4.4
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  backend:
    container_name: modellfabrik_backend
    hostname: modellfabrik-backend
    build: ./server
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment: 
      WAIT_HOSTS: modellfabrik-db:27017

  frontend:
    container_name: modellfabrik_frontend
    hostname: modellfabrik-frontend
    build: ./client
    depends_on:
      - backend
    ports:
      - "8080:8080"
    environment: 
      WAIT_HOSTS: modellfabrik-backend:3000
